resources:
- https://github.com/LetUsSeng/kustomize-base//nginx/base/?ref=v1.0.1


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

patches:
- path: replica-count.yaml
- path: hpa-setting.yaml

images:
- name: nginx
  newName: nginx
  newTag: latest